sudo: false
services:
  - docker
language: python
python:
  - "2.7"
  - "3.6"
install:
  - travis_retry pip install --user pylint
  - travis_retry pip install --user -r requirements.txt
before_script:
  - pylint --version
script:
  - pylint *.py -r y
